name: PlotsX
version: '${project.version}'
main: com.plotsx.PlotsX
api-version: '1.20'
depend: [Vault]
softdepend: [CoreProtect]
author: Wupas94
description: Zaawansowany system działek z wieloma funkcjami
website: https://github.com/Wupas94/PlotsX

commands:
  plot:
    description: Główna komenda do zarządzania działkami
    usage: |
      §6PlotsX - Lista komend:
      §e/plot claim §7- Zajmij działkę
      §e/plot delete §7- Usuń działkę
      §e/plot home §7- Teleportuj się na działkę
      §e/plot info §7- Informacje o działce
      §e/plot list §7- Lista twoich działek
      §e/plot trust <gracz> §7- Dodaj zaufanego gracza
      §e/plot untrust <gracz> §7- Usuń zaufanego gracza
      §e/plot visit <gracz> §7- Odwiedź działkę gracza
      §e/plot rate <1-5> §7- Oceń działkę
      §e/plot flags §7- Zarządzaj flagami działki
      §e/plot biome §7- Zmień biom działki
    aliases: [p, plots, plotsx]

permissions:
  plotsx.*:
    description: Dostęp do wszystkich funkcji pluginu
    children:
      plotsx.admin: true
      plotsx.user: true
      plotsx.coreprotect.*: true
  
  plotsx.admin:
    description: Dostęp do komend administracyjnych
    children:
      plotsx.admin.bypass: true
      plotsx.admin.reload: true
      plotsx.admin.delete.other: true
      plotsx.admin.manage.other: true
      plotsx.admin.schematic.preset: true

  # CoreProtect Integration
  plotsx.coreprotect.*:
    description: Dostęp do funkcji CoreProtect
    children:
      plotsx.coreprotect.lookup: true
      plotsx.coreprotect.rollback: true
      plotsx.coreprotect.restore: true
      plotsx.coreprotect.inspect: true

  plotsx.user:
    description: Dostęp do podstawowych komend
    children:
      plotsx.plot.claim: true
      plotsx.plot.delete: true
      plotsx.plot.home: true
      plotsx.plot.info: true
      plotsx.plot.list: true
      plotsx.plot.trust: true
      plotsx.plot.untrust: true
      plotsx.plot.visit: true
      plotsx.plot.rate: true
      plotsx.plot.flags: true
      plotsx.plot.biome: true
  
  # Level System
  plotsx.level.*:
    description: Dostęp do systemu poziomów
    children:
      plotsx.level.upgrade: true
      plotsx.level.info: true
  
  # Visit System
  plotsx.visit.*:
    description: Dostęp do systemu wizyt
    children:
      plotsx.visit.teleport: true
      plotsx.visit.rate: true
      plotsx.visit.setspawn: true
      plotsx.visit.top: true
  
  # Flag System
  plotsx.flags.*:
    description: Dostęp do systemu flag
    children:
      plotsx.flags.set: true
      plotsx.flags.weather: true
      plotsx.flags.time: true
      plotsx.flags.mobs: true
      plotsx.flags.particles: true
      plotsx.flags.feed: true
      plotsx.flags.messages: true
  
  # Schematic System
  plotsx.schematic.*:
    description: Dostęp do systemu schematów
    children:
      plotsx.schematic.save: true
      plotsx.schematic.load: true
      plotsx.schematic.backup: true
      plotsx.schematic.restore: true
      plotsx.schematic.copy: true
  
  # Trust System
  plotsx.trust.*:
    description: Dostęp do systemu zaufanych graczy
    children:
      plotsx.trust.add: true
      plotsx.trust.remove: true
      plotsx.trust.list: true
      plotsx.trust.temp: true
  
  # Task System
  plotsx.tasks.*:
    description: Dostęp do systemu zadań
    children:
      plotsx.tasks.view: true
      plotsx.tasks.progress: true
      plotsx.tasks.complete: true
      plotsx.tasks.rewards: true
  
  # Economy System
  plotsx.economy.*:
    description: Dostęp do systemu ekonomii
    children:
      plotsx.economy.sell: true
      plotsx.economy.buy: true
      plotsx.economy.rent: true
      plotsx.economy.auction: true
      plotsx.economy.shop: true
  
  # Biome System
  plotsx.biome.*:
    description: Dostęp do systemu biomów
    children:
      plotsx.biome.set: true
      plotsx.biome.growth: true
      plotsx.biome.mobs: true
      plotsx.biome.spread: true 