name: PlotsX
version: '${project.version}'
main: com.plotsx.PlotsX
api-version: '1.20'
authors: [grzli]
description: A comprehensive plot management plugin for Minecraft servers
website: https://github.com/grzli/PlotsX
depend: [Vault, CoreProtect]
commands:
  plot:
    description: Main command for plot management
    usage: /<command> [subcommand]
    aliases: [plots, plotx]
    permission: plotsx.use
permissions:
  plotsx.use:
    description: Allows using basic plot commands
    default: true
  plotsx.admin:
    description: Allows using admin plot commands
    default: op
  plotsx.bypass:
    description: Allows bypassing plot restrictions
    default: op
  plotsx.claim:
    description: Allows claiming plots
    default: true
  plotsx.delete:
    description: Allows deleting plots
    default: true
  plotsx.trust:
    description: Allows managing plot trust
    default: true
  plotsx.untrust:
    description: Allows removing plot trust
    default: true
  plotsx.flags:
    description: Allows managing plot flags
    default: true
  plotsx.biome:
    description: Allows changing plot biome
    default: true
  plotsx.weather:
    description: Allows changing plot weather
    default: true
  plotsx.time:
    description: Allows changing plot time
    default: true
  plotsx.border:
    description: Allows toggling plot border
    default: true
  plotsx.expand:
    description: Allows expanding plots
    default: true
  plotsx.shrink:
    description: Allows shrinking plots
    default: true
  plotsx.move:
    description: Allows moving plots
    default: true
  plotsx.merge:
    description: Allows merging plots
    default: true
  plotsx.split:
    description: Allows splitting plots
    default: true
  plotsx.swap:
    description: Allows swapping plots
    default: true
  plotsx.clear:
    description: Allows clearing plots
    default: true
  plotsx.reset:
    description: Allows resetting plots
    default: true
  plotsx.save:
    description: Allows saving plot schematics
    default: true
  plotsx.load:
    description: Allows loading plot schematics
    default: true
  plotsx.list:
    description: Allows listing plots
    default: true
  plotsx.search:
    description: Allows searching plots
    default: true
  plotsx.stats:
    description: Allows viewing plot statistics
    default: true
  plotsx.sell:
    description: Allows selling plots
    default: true
  plotsx.buy:
    description: Allows buying plots
    default: true
  plotsx.rent:
    description: Allows renting plots
    default: true
  plotsx.tasks:
    description: Allows managing plot tasks
    default: true
  plotsx.rewards:
    description: Allows managing plot rewards
    default: true
  plotsx.rate:
    description: Allows rating plots
    default: true
  plotsx.visit:
    description: Allows visiting plots
    default: true
  plotsx.home:
    description: Allows teleporting to plot home
    default: true

# CoreProtect Integration
plotsx.coreprotect.*:
  description: Dostęp do funkcji CoreProtect
  default: op
  children:
    plotsx.coreprotect.lookup: true
    plotsx.coreprotect.rollback: true
    plotsx.coreprotect.restore: true
    plotsx.coreprotect.inspect: true

# Level System
plotsx.level.*:
  description: Dostęp do systemu poziomów
  default: true
  children:
    plotsx.level.upgrade: true
    plotsx.level.info: true

# Visit System
plotsx.visit.*:
  description: Dostęp do systemu wizyt
  default: true
  children:
    plotsx.visit.teleport: true
    plotsx.visit.rate: true
    plotsx.visit.setspawn: true
    plotsx.visit.top: true

# Flag System
plotsx.flags.*:
  description: Dostęp do systemu flag
  default: true
  children:
    plotsx.flags.set: true
    plotsx.flags.weather: true
    plotsx.flags.time: true
    plotsx.flags.mobs: true
    plotsx.flags.particles: true
    plotsx.flags.feed: true
    plotsx.flags.messages: true

# Schematic System
plotsx.schematic.*:
  description: Dostęp do systemu schematów
  default: op
  children:
    plotsx.schematic.save: true
    plotsx.schematic.load: true
    plotsx.schematic.backup: true
    plotsx.schematic.restore: true
    plotsx.schematic.copy: true

# Trust System
plotsx.trust.*:
  description: Dostęp do systemu zaufanych graczy
  default: true
  children:
    plotsx.trust.add: true
    plotsx.trust.remove: true
    plotsx.trust.list: true
    plotsx.trust.temp: true

# Task System
plotsx.tasks.*:
  description: Dostęp do systemu zadań
  default: true
  children:
    plotsx.tasks.view: true
    plotsx.tasks.progress: true
    plotsx.tasks.complete: true
    plotsx.tasks.rewards: true

# Economy System
plotsx.economy.*:
  description: Dostęp do systemu ekonomii
  default: true
  children:
    plotsx.economy.sell: true
    plotsx.economy.buy: true
    plotsx.economy.rent: true
    plotsx.economy.auction: true
    plotsx.economy.shop: true

# Biome System
plotsx.biome.*:
  description: Dostęp do systemu biomów
  default: true
  children:
    plotsx.biome.set: true
    plotsx.biome.growth: true
    plotsx.biome.mobs: true
    plotsx.biome.spread: true

# Notification System
plotsx.notification.*:
  description: Dostęp do systemu powiadomień
  default: op
  children:
    plotsx.notification.receive: true
    plotsx.notification.send: true
    plotsx.notification.clear: true
    plotsx.notification.list: true
    plotsx.notification.priority: true

# Metrics System
plotsx.metrics.*:
  description: Dostęp do systemu metryk
  default: op
  children:
    plotsx.metrics.view: true
    plotsx.metrics.clear: true
    plotsx.metrics.export: true
    plotsx.metrics.health: true

# Backup System
plotsx.backup.*:
  description: Dostęp do systemu kopii zapasowych
  default: op
  children:
    plotsx.backup.create: true
    plotsx.backup.restore: true
    plotsx.backup.delete: true
    plotsx.backup.list: true
    plotsx.backup.auto: true

# Cache System
plotsx.cache.*:
  description: Dostęp do systemu cache
  default: op
  children:
    plotsx.cache.view: true
    plotsx.cache.clear: true
    plotsx.cache.stats: true
    plotsx.cache.optimize: true

# Async System
plotsx.async.*:
  description: Dostęp do systemu asynchronicznego
  default: op
  children:
    plotsx.async.view: true
    plotsx.async.clear: true
    plotsx.async.stats: true
    plotsx.async.optimize: true

# Uprawnienia administracyjne
plotsx.admin.reload:
  description: Pozwala na przeładowanie pluginu
  default: op
plotsx.admin.save:
  description: Pozwala na zapisanie wszystkich danych
  default: op
plotsx.admin.load:
  description: Pozwala na załadowanie wszystkich danych
  default: op
plotsx.admin.clear:
  description: Pozwala na wyczyszczenie wszystkich danych
  default: op
plotsx.admin.reset:
  description: Pozwala na zresetowanie wszystkich danych
  default: op
plotsx.admin.delete:
  description: Pozwala na usunięcie działki
  default: op
plotsx.admin.give:
  description: Pozwala na nadanie działki
  default: op
plotsx.admin.take:
  description: Pozwala na odebranie działki
  default: op
plotsx.admin.setowner:
  description: Pozwala na ustawienie właściciela działki
  default: op
plotsx.admin.setbiome:
  description: Pozwala na ustawienie biomu działki
  default: op
plotsx.admin.setweather:
  description: Pozwala na ustawienie pogody na działce
  default: op
plotsx.admin.settime:
  description: Pozwala na ustawienie czasu na działce
  default: op
plotsx.admin.setborder:
  description: Pozwala na ustawienie granic działki
  default: op
plotsx.admin.expand:
  description: Pozwala na rozszerzenie działki
  default: op
plotsx.admin.shrink:
  description: Pozwala na zmniejszenie działki
  default: op
plotsx.admin.move:
  description: Pozwala na przeniesienie działki
  default: op
plotsx.admin.merge:
  description: Pozwala na połączenie działek
  default: op
plotsx.admin.split:
  description: Pozwala na podział działki
  default: op
plotsx.admin.swap:
  description: Pozwala na zamianę miejscami działek
  default: op
plotsx.admin.list:
  description: Pozwala na wyświetlenie listy wszystkich działek
  default: op
plotsx.admin.search:
  description: Pozwala na wyszukiwanie działek
  default: op
plotsx.admin.stats:
  description: Pozwala na wyświetlenie statystyk pluginu
  default: op
plotsx.admin.notifications:
  description: Pozwala na zarządzanie powiadomieniami
  default: op
plotsx.admin.metrics:
  description: Pozwala na zarządzanie metrykami
  default: op
plotsx.admin.backup:
  description: Pozwala na zarządzanie kopiami zapasowymi
  default: op
plotsx.admin.cache:
  description: Pozwala na zarządzanie cache
  default: op
plotsx.admin.async:
  description: Pozwala na zarządzanie systemem asynchronicznym
  default: op

# Uprawnienia użytkownika
plotsx.user:
  description: Dostęp do podstawowych komend
  default: true
  children:
    plotsx.plot.claim: true
    plotsx.plot.delete: true
    plotsx.plot.home: true
    plotsx.plot.info: true
    plotsx.plot.list: true
    plotsx.plot.trust: true
    plotsx.plot.untrust: true
    plotsx.plot.visit: true
    plotsx.plot.rate: true
    plotsx.plot.flags: true
    plotsx.plot.biome: true

# Uprawnienia powiadomień
plotsx.notification.receive:
  description: Pozwala na otrzymywanie powiadomień
  default: op
plotsx.notification.send:
  description: Pozwala na wysyłanie powiadomień
  default: op
plotsx.notification.clear:
  description: Pozwala na czyszczenie powiadomień
  default: op
plotsx.notification.list:
  description: Pozwala na wyświetlenie listy powiadomień
  default: op
plotsx.notification.priority:
  description: Pozwala na zarządzanie priorytetami powiadomień
  default: op

# Uprawnienia metryk
plotsx.metrics.view:
  description: Pozwala na wyświetlenie metryk
  default: op
plotsx.metrics.clear:
  description: Pozwala na czyszczenie metryk
  default: op
plotsx.metrics.export:
  description: Pozwala na eksport metryk
  default: op
plotsx.metrics.health:
  description: Pozwala na sprawdzanie zdrowia pluginu
  default: op

# Uprawnienia kopii zapasowych
plotsx.backup.create:
  description: Pozwala na tworzenie kopii zapasowych
  default: op
plotsx.backup.restore:
  description: Pozwala na przywracanie kopii zapasowych
  default: op
plotsx.backup.delete:
  description: Pozwala na usuwanie kopii zapasowych
  default: op
plotsx.backup.list:
  description: Pozwala na wyświetlenie listy kopii zapasowych
  default: op
plotsx.backup.auto:
  description: Pozwala na zarządzanie automatycznymi kopiami zapasowymi
  default: op

# Uprawnienia cache
plotsx.cache.view:
  description: Pozwala na wyświetlenie stanu cache
  default: op
plotsx.cache.clear:
  description: Pozwala na czyszczenie cache
  default: op
plotsx.cache.stats:
  description: Pozwala na wyświetlenie statystyk cache
  default: op
plotsx.cache.optimize:
  description: Pozwala na optymalizację cache
  default: op

# Uprawnienia asynchroniczne
plotsx.async.view:
  description: Pozwala na wyświetlenie stanu systemu asynchronicznego
  default: op
plotsx.async.clear:
  description: Pozwala na czyszczenie kolejki zadań asynchronicznych
  default: op
plotsx.async.stats:
  description: Pozwala na wyświetlenie statystyk systemu asynchronicznego
  default: op
plotsx.async.optimize:
  description: Pozwala na optymalizację systemu asynchronicznego
  default: op 